server {
    listen 80;
    server_name _; # Reemplaza con tu dominio o IP

    root /var/www/html/feria_campo_soberano/dist; # Reemplaza con la ruta real en tu servidor
    index index.html;

    # Gzip compresión para mejorar el rendimiento
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;
    gzip_disable "MSIE [1-6]\.";

    # Configuración para la aplicación de una sola página (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configurar la caché para recursos estáticos (CSS, JS, imágenes)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Seguridad: Denegar acceso a archivos ocultos (como .env)
    location ~ /\. {
        deny all;
    }
}
